version: "3.7"

services:
    redis:
        image: redis:6.2-alpine
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
        - redis:/data
        
    rails:
        build: .
        image: web-cw-group-24-mailer
        ports:
            - 3002:3000
        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
        volumes:
            - .:/app
        depends_on:
            - redis
        links:
            - redis
        
    sidekiq:
        depends_on:
        - 'redis'
        build: .
        command: sidekiq -C config/sidekiq.yml
        volumes:
        - '.:/app'


volumes:
    redis: 
        driver: local
