version: "3.7"

services:
    db_auth:
        image: mysql:5.7
        # volumes: 
        #     - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_DATABASE: auth
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: group24
            MYSQL_TCP_PORT:  3307:3306

        ports:
            - 3307:3306

    
    rails:
        build: .
        image: web-cw-group-24-mailer
        ports:
            - 3000:3000
        volumes:
            - .:/app
        depends_on:
            - db_auth
        links:
            - db_auth
